 matrix:
   include:
      sudo: required
    - language: java
      jdk: oraclejdk11
      services:
       - postgresql
      before_install:
       - chmod og+rX /backend
       - cd backend/
       - chmod +x mvnw
       - psql -c 'create database recruitment;' -U postgres
       - sudo -u postgres psql -c "CREATE USER recruitment_acc WITH ENCRYPTED PASSWORD '123123';"
       - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE recruitment TO recruitment_acc;"

    - language: node_js
      node_js:
       - 'stable'
      cache:
      directories:
       - 'node_modules'
      before_install:
       - cd frontend/
      install:
       - npm install
      env:
      global:
       - NODE_ENV=test
      before_script:
       - npm run build
      script:
       - npm test
notifications:
  email: false