export const GET_APPLICATION = 'GET_APPLICATION';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS';
export const APPLICATION_ERROR = 'APPLICATION_ERROR';
export const CLEAR_APPLICATION = 'CLEAR_APPLICATION';
